### ISSUE TITLE
Building Universal Windows Platforms Apps (Sample Code)

### ISSUE THREAD

**Issue by javisoft** [colinizer/foodwheels#1]
Hi,
The Live Lessons tutorial references this repo to download the sample code. Any idea when is it going to be available?
Thanks

**Comment by colinizer** [comment]
It will be up this week.  Sorry for the delay.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by javisoft** [comment]
Any update?
Thanks,
Javier

**Comment by colinizer** [comment]
Just removing final graphic  assets that cannot be published for licensing reasons.

Sent from my Windows 10 phone

**Comment by javisoft** [comment]
I really enjoyed your UWP course. Can't wait to play with the code! Great
Job! Thanks.

**Comment by colinizer** [comment]
Great.  Was it 12 hours to complete?

Feel free to rate it once you get the code.

Sent from my Windows 10 phone

**Comment by javisoft** [comment]
Will do. It took me ~ 14 hours
